database_url = "postgres://postgres:password@localhost:5432/blog"
secret = "secret"
port = 3000
host = "0.0.0.0"
rust_log = "info"
jwt_expiration_min = 86400
run_migrations = true
save_dir = "static/posts"
migrate_dir = "migrations"